# Generated by Django 5.0.6 on 2024-07-09 00:46

import gateway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_data_alter_report_table_alter_system_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.JSONField(default=gateway.models.default_data, verbose_name='Entry'),
        ),
    ]
