# Generated by Django 4.2.14 on 2024-07-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_mytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
